<a href="https://colab.research.google.com/github/shusank8/GPT/blob/main/GPT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("GPT BY SHUSANKET BASYAL")

GPT BY SHUSANKET BASYAL


In [ ]:
# GPT BASICS USING SIMPLE NUMBERS

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

In [ ]:
B,T,C = 4,8,2
x = torch.randn(B,T,C)

In [ ]:
wei = torch.tril(torch.ones(T,T))
wei = wei/torch.sum(wei,1, keepdim=True)
      # (T,T) @ (B,T,C)=>(B,T,C)
out  = wei @ x

In [ ]:
wei

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [ ]:
x[0]

tensor([[ 0.8135,  0.1395],
        [ 0.8426, -0.7039],
        [-0.2040,  0.8776],
        [-1.1508,  1.3973],
        [-2.3654, -1.1355],
        [ 2.1224, -0.6362],
        [ 0.2226,  0.7333],
        [ 1.6990, -0.0056]])

In [ ]:
out[0]

tensor([[ 0.8135,  0.1395],
        [ 0.8281, -0.2822],
        [ 0.4840,  0.1044],
        [ 0.0753,  0.4276],
        [-0.4128,  0.1150],
        [ 0.0097, -0.0102],
        [ 0.0401,  0.0960],
        [ 0.2475,  0.0833]])

In [ ]:

tril = torch.tril(torch.ones(T,T))
wei = torch.zeros((T,T))
wei1 = wei.masked_fill(tril==0, float("-inf"))
wei2 = F.softmax(wei1, dim=1)

In [ ]:
wei[3]

tensor([0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
wei1[3]

tensor([0., 0., 0., 0., -inf, -inf, -inf, -inf])

In [ ]:
wei2[3]

tensor([0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000])

In [ ]:
wei1[3].exp()/wei1[3].exp().sum()

tensor([0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000])

In [ ]:
# self-attention


# single head of self attention
head_size = 16
key = nn.Linear(C, head_size, bias = False)
query = nn.Linear(C, head_size, bias = False)
# x=>(B,T,C) AND K => (B,T,HEAD_SIZE)
k = key(x)
# x=>(B,T,C) AND K => (B,T,HEAD_SIZE)
q = query(x)

# (q = > (B,T,HEADSIZE) @ K.TRANSPOSE=> (B,HEADSIZE, T))=>(B,T,T)
wei11 = q @k.transpose(-2,-1)


tril = torch.tril(torch.ones(T,T))

wei21 = wei11.masked_fill(tril==0, float("-inf"))

wei31 = F.softmax(wei21, dim=-1)
# out = wei@x


In [ ]:
wei11.shape

torch.Size([4, 8, 8])

In [ ]:
wei11[0][3]

tensor([ 0.1093,  0.0458,  0.0357, -0.0044, -0.0587, -0.0421,  0.0445,  0.0540],
       grad_fn=<SelectBackward0>)

In [ ]:
wei21[0][3]

tensor([ 0.1093,  0.0458,  0.0357, -0.0044,    -inf,    -inf,    -inf,    -inf],
       grad_fn=<SelectBackward0>)

In [ ]:
wei31[0][3]

tensor([0.2660, 0.2496, 0.2471, 0.2374, 0.0000, 0.0000, 0.0000, 0.0000],
       grad_fn=<SelectBackward0>)

In [ ]:
wei31.shape, x.shape

(torch.Size([4, 8, 8]), torch.Size([4, 8, 2]))

In [ ]:
wei31[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4601, 0.5399, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2708, 0.3384, 0.3908, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2660, 0.2496, 0.2471, 0.2374, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1241, 0.0993, 0.0760, 0.2435, 0.4572, 0.0000, 0.0000, 0.0000],
        [0.0999, 0.0888, 0.0727, 0.1878, 0.3231, 0.2277, 0.0000, 0.0000],
        [0.1291, 0.1673, 0.2010, 0.1060, 0.0799, 0.1006, 0.2161, 0.0000],
        [0.1203, 0.1476, 0.1886, 0.0645, 0.0361, 0.0535, 0.2155, 0.1739]],
       grad_fn=<SelectBackward0>)

In [ ]:
x[0]

tensor([[ 1.3195, -1.2473],
        [ 1.0026,  0.3587],
        [ 1.1769,  1.0539],
        [-0.2901, -0.4149],
        [-1.3584, -0.6015],
        [-0.8044, -0.0989],
        [ 1.3915,  1.1649],
        [ 1.2447,  0.5451]])